import './components/layout';
import './components/employee-form/employee-form';
import './components/employee-list/employee-list';
import './components/employee-list/employee-cards/employee-cards';
import './components/employee-list/employee-table/employee-table';
import './pages/create-employee';
import './pages/update-employee';
import './pages/landing-page';
import './components/employee-list/employee-list';